---
title: "Integrated Monitoring and Early Warning of Land Subsidence and Extreme Flood Risks"
subtitle: "Ho Chi Minh City, Vietnam"
author: "Da, HoMan, Jiajun, Ruijue, Zhihao"
institute: "CASA"
date: "2026/03/24"
output:
  xaringan::moon_reader:
    css: custom.css
    lib_dir: libs
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
    
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-all, echo=FALSE, warning=FALSE}
library(xaringan)
library(xaringanExtra)
library(knitr)

xaringanExtra::use_search(show_icon = TRUE, auto_search	=FALSE)
xaringanExtra::use_tile_view()
xaringanExtra::use_fit_screen()
xaringanExtra::use_clipboard()
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         
  mute_unhighlighted_code = TRUE  
)
xaringanExtra::use_panelset()
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#1c5253",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

class: inverse, center, middle

# Problem Definition

---

# Background

### Ho Chi Minh City

---

class: inverse, center, middle

# Project Approach

---

class: inverse, center, middle

# Project plan, risks and value for money